<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="omni_robot">
  
  <xacro:property name="robot_name" value="$(arg robot_name)" />
  <xacro:property name="wheel_radius" value="0.05" />
  <xacro:property name="wheel_width" value="0.02" />
  <xacro:property name="base_radius" value="0.2" />
  <xacro:property name="base_height" value="0.1" />
  <xacro:property name="PI" value="3.1415926535897931" />
  
  <link name="${robot_name}/base_footprint"/>
  
  <link name="${robot_name}/base_link">
    <visual>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 0.8"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>
  
  <joint name="${robot_name}/base_joint" type="fixed">
    <parent link="${robot_name}/base_footprint"/>
    <child link="${robot_name}/base_link"/>
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
  </joint>
  
  <link name="${robot_name}/omni_wheel_1">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black">
        <color rgba="0.2 0.2 0.2 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>
  
  <joint name="${robot_name}/omni_wheel_1_joint" type="continuous">
    <parent link="${robot_name}/base_link"/>
    <child link="${robot_name}/omni_wheel_1"/>
    <origin xyz="${base_radius*0.8} 0 ${-base_height/2}" rpy="${PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>
  
  <link name="${robot_name}/omni_wheel_2">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black">
        <color rgba="0.2 0.2 0.2 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>
  
  <joint name="${robot_name}/omni_wheel_2_joint" type="continuous">
    <parent link="${robot_name}/base_link"/>
    <child link="${robot_name}/omni_wheel_2"/>
    <origin xyz="${base_radius*0.8*cos(2.094)} ${base_radius*0.8*sin(2.094)} ${-base_height/2}" 
            rpy="${PI/2} 0 2.094"/>
    <axis xyz="0 0 1"/>
  </joint>
  
  <link name="${robot_name}/omni_wheel_3">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black">
        <color rgba="0.2 0.2 0.2 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>
  
  <joint name="${robot_name}/omni_wheel_3_joint" type="continuous">
    <parent link="${robot_name}/base_link"/>
    <child link="${robot_name}/omni_wheel_3"/>
    <origin xyz="${base_radius*0.8*cos(4.189)} ${base_radius*0.8*sin(4.189)} ${-base_height/2}" 
            rpy="${PI/2} 0 4.189"/>
    <axis xyz="0 0 1"/>
  </joint>
  
  <link name="${robot_name}/laser">
    <visual>
      <geometry>
        <cylinder radius="0.03" length="0.04"/>
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.03" length="0.04"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>
  
  <joint name="${robot_name}/laser_joint" type="fixed">
    <parent link="${robot_name}/base_link"/>
    <child link="${robot_name}/laser"/>
    <origin xyz="0 0 ${base_height/2 + 0.02}" rpy="0 0 0"/>
  </joint>
  
  <link name="${robot_name}/imu_link">
    <visual>
      <geometry>
        <box size="0.02 0.02 0.01"/>
      </geometry>
      <material name="green">
        <color rgba="0 1 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.02 0.02 0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>
  
  <joint name="${robot_name}/imu_joint" type="fixed">
    <parent link="${robot_name}/base_link"/>
    <child link="${robot_name}/imu_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>
  
  <gazebo>
    <plugin name="omni_drive_controller" filename="libgazebo_ros_planar_move.so">
      <robotNamespace>/${robot_name}</robotNamespace>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>${robot_name}/odom</odometryFrame>
      <robotBaseFrame>${robot_name}/base_footprint</robotBaseFrame>
      <odometryRate>50.0</odometryRate>
      <publishTF>true</publishTF>
    </plugin>
  </gazebo>
  
  <gazebo reference="${robot_name}/laser">
    <sensor type="ray" name="laser_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>20</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>8.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_laser" filename="libgazebo_ros_laser.so">
        <topicName>/${robot_name}/scan</topicName>
        <frameName>${robot_name}/laser</frameName>
      </plugin>
    </sensor>
  </gazebo>
  
  <gazebo reference="${robot_name}/imu_link">
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <visualize>true</visualize>
      <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
        <topicName>/${robot_name}/imu</topicName>
        <bodyName>${robot_name}/imu_link</bodyName>
        <updateRateHZ>100.0</updateRateHZ>
        <gaussianNoise>0.0</gaussianNoise>
        <xyzOffset>0 0 0</xyzOffset>
        <rpyOffset>0 0 0</rpyOffset>
        <frameName>${robot_name}/imu_link</frameName>
      </plugin>
    </sensor>
  </gazebo>
  
  <gazebo reference="${robot_name}/omni_wheel_1">
    <material>Gazebo/Black</material>
    <mu1>0.1</mu1>
    <mu2>0.1</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <minDepth>0.001</minDepth>
    <maxVel>1.0</maxVel>
  </gazebo>
  
  <gazebo reference="${robot_name}/omni_wheel_2">
    <material>Gazebo/Black</material>
    <mu1>0.1</mu1>
    <mu2>0.1</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <minDepth>0.001</minDepth>
    <maxVel>1.0</maxVel>
  </gazebo>
  
  <gazebo reference="${robot_name}/omni_wheel_3">
    <material>Gazebo/Black</material>
    <mu1>0.1</mu1>
    <mu2>0.1</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <minDepth>0.001</minDepth>
    <maxVel>1.0</maxVel>
  </gazebo>
  
  <gazebo reference="${robot_name}/base_link">
    <material>Gazebo/Blue</material>
  </gazebo>
  
</robot>
